FROM node:13.12.0-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./
RUN npm install

COPY . ./

# Replace with http://api.weatherstack.com/ API KEY
ENV REACT_APP_API_KEY = 'API KEY'

CMD ["npm", "start"]